apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: application
  labels:
    env: Production
    owner: AntonYaskov
spec:
  selector:
    project: api
  ports:
    - name: api-listener
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
  namespace: application
  labels:
    env: Production
    owner: AntonYaskov
spec:
  selector:
    project: front
  ports:
    - name: front-listener
      protocol: TCP
      port: 3000
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db-service
  namespace: application
  labels:
    app: postgres-db-service
spec:
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    app: postgres-db
