apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: application
  labels:
    app: api-application
    env: Production
    owner: AntonYaskov
spec:
  replicas: 1
  selector:
    matchLabels:
      project: api
  template:
    metadata:
      labels:
        project: api
    spec:
      containers:
        - name: application-back
          image: fnatikjk/back_crm_66bit:latest
          ports:
            - containerPort: 80
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Debug
          - name: HOST
            value: "request.stk8s.66bit.ru"
          - name: DATABASE_CONNECTION
            value: "host=postgres-db-service;port=5432;database=CRM66bit;username=postgres;password=password"
          - name: MAILBOX_LOGIN
            value: "chernorusy@mail.ru"
          - name: MAILBOX_PASSWORD
            value: "KGw9Q2bmFZpyptJ4xfKZ"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: application
  labels:
    app: front-application
    env: Production
    owner: AntonYaskov
spec:
  replicas: 1
  selector:
    matchLabels:
      project: front
  template:
    metadata:
      labels:
        project: front
    spec:
      containers:
        - name: application-front
          image: iceneo/chernorusy-fron1:latest
          ports:
            - containerPort: 80
          env:
          - name: API_URL
            value: "request.stk8s.66bit.ru"
          - name: API_PROTOCOL
            value: "https"
          - name: API_CHAT_HUB_URL 
            value: "Hubs/Chats"
          - name: API_CRM_HUB_URL
            value: "Hubs/Crm"
