version: '3.9'

networks:
  Crm-dev: ### NETWORK - variable
    driver: bridge 

services:
  postgres_db: ### DB_SERVICE - variable
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "CRM66bit"
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - ${NETWORK}

  backend:
    image: ${BACKEND_IMAGE}
    depends_on:
      - ${DB_SERVICE}
    ports:
      - "90:90"
    environment:
      HOST: "localhost:90"
      DATABASE_CONNECTION: "host=${DB_SERVICE};port=5432;database=CRM66bit;username=postgres;password=password"
      MAILBOX_LOGIN: "chernorusy@mail.ru"
      MAILBOX_PASSWORD: "KGw9Q2bmFZpyptJ4xfKZ"
    networks:
      - ${NETWORK}

  front:
    image: ${FRONT_IMAGE}
    ports:
      - "80:80"
    expose:
      - 80
    environment:
      API_URL: ${API_URL}
      API_PROTOCOL: ${API_PROTOCOL}
    networks:
      - ${NETWORK}
  
  
volumes:
  db_volume: